name: flutter_module
description: A new Flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  # Icons
  ionicons: ^0.2.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:

flutter:
  uses-material-design: true
  # generate: true
  assets:
    - assets/

  module:
    androidX: true
    androidPackage: fr.cashbee.flutter_module
    iosBundleIdentifier: fr.cashbee.flutterModule
